### ISSUE TITLE
AVACL 用户权限控制

### ISSUE THREAD

**Issue by taosimple** [LunaGao/AnyTime#1]
你好，我现在也在用leancloud做应用的后台。我看你们注册的时候都没有设置`AVACL`,控制台看的权限都是 `{"*":{"read":true,"write":true}}`，官方文档是这样说的
`请注意，新创建应用的 _User 表的查询权限默认是关闭的，通常我们推荐你在云引擎里封装用户查询，只查询特定条件的用户，避免开放用户表的全部查询权限。此外，你可以通过 class 权限设置打开查询权限，请参考 数据与安全 - Class 级别的权限。`
，但是后台看到的是读写权限全开的，不知道正确的实践是怎样的？

**Comment by lzwjava** [comment]
@daweibayu  这里有个issue ^

**Comment by daweibayu** [comment]
关于权限可以查阅文档 https://leancloud.cn/docs/acl_guide-android.html 。
如有不明白的地方可以随时提出，我们再进行解答。
如有问题可以反馈到 论坛 https://forum.leancloud.cn/ 或者工单 https://ticket.leancloud.cn/。

**Comment by LunaGao** [comment]
@taosimple 请参考官方网站的推荐进行操作。这个demo中的样例只是在学习，目标只是功能达到即可，并未对真实应用的安全性等方面进行考虑。
